### PR TITLE
Add "off" method

### PR DESCRIPTION
**Pull request by misog**

### CODE REVIEW

**Comment by dieulot** [comment]
Do you know when that would be useful? If it has no concrete usefulness I'm not merging it in.

**Comment by misog** [comment]
It would be useful when various subpages add own events which should not be global. I use off method to reset all events.

**Comment by dieulot** [comment]
I’m not sure what you mean by subpages. I’m still unable to visualize where that would be useful. Could you give me more details on how your site, with its subpages, works? (Optionally, with a link.)

**Comment by misog** [comment]
Use case:
- a.html is loaded (by instantclick or first load)
- a.html contains InstantClick.on('change', whateverFunction);
- when b.html is loaded by instantclick, whateverFunction is called (OK)
- when c.html is loaded by instantclick, whateverFunction should not be called - how to implement this?
One solution is to remove the whateverFunction from the eventsCallbacks array by the off method.

**Comment by dieulot** [comment]
Thanks.

I would use `whateverFunction()` directly, not through InstantClick’s change event, on A and B, and not on C.

Would that work for your use case? If not, why?

**Pull request closed without merging**
